"""empty message

Revision ID: 2d49572c7884
Revises: c3f66ac80c8b
Create Date: 2021-05-28 10:19:43.345116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d49572c7884'
down_revision = 'c3f66ac80c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
