"""empty message

Revision ID: 455970924ed2
Revises: ab6b56596f03
Create Date: 2021-05-28 18:10:58.753066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '455970924ed2'
down_revision = 'ab6b56596f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_datetime', sa.DateTime(), nullable=False))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'start_datetime')
    # ### end Alembic commands ###
